apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "9.11.1"
    values:
      nginx-ingress:
        enabled: true
      global:
        hosts:
          domain: 127-0-0-1.nip.io
          https: false
        ingress:
          configureCertmanager: false
          tls:
            enabled: false
      certmanager:
        install: false