apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-a
spec:
  instances: 1

  storage:
    size: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  postgresql:
    parameters:
      shared_buffers: "64MB"
      max_connections: "30"