apiVersion: v1
kind: Service
metadata:
  name: pg-a-nodeport
  namespace: database
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: pg-a
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432